/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.softwarebodega.vista;

/**
 *
 * @author Aaron
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSuperior = new javax.swing.JPanel();
        jpOpciones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 67, 68));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSuperior.setBackground(new java.awt.Color(141, 230, 238));
        jpSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jpSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 90));

        jpOpciones.setBackground(new java.awt.Color(141, 230, 238));
        jpOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Compras");
        jpOpciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 40));

        jButton2.setText("Ventas");
        jpOpciones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 40));

        jButton3.setText("Clientes");
        jpOpciones.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 40));

        jButton4.setText("Usuarios");
        jpOpciones.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 40));

        jButton5.setText("Productos");
        jpOpciones.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 40));

        jButton6.setText("Proveedores");
        jpOpciones.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, 40));

        jButton7.setText("Almacen");
        jpOpciones.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 40));

        getContentPane().add(jpOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jpOpciones;
    private javax.swing.JPanel jpSuperior;
    // End of variables declaration//GEN-END:variables
}
