/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.softwarebodega.vista;

/**
 *
 * @author Aaron
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSuperior = new javax.swing.JPanel();
        jpOpciones = new javax.swing.JPanel();
        jbtnCompras = new javax.swing.JButton();
        jbtnVentas = new javax.swing.JButton();
        jbtnClientes = new javax.swing.JButton();
        jbtnUsuarios = new javax.swing.JButton();
        jbtnProductos = new javax.swing.JButton();
        jbtnProveedores = new javax.swing.JButton();
        jbtnAlmacen = new javax.swing.JButton();
        jdpContenerdor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bodega");
        setBackground(new java.awt.Color(66, 67, 68));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSuperior.setBackground(new java.awt.Color(139, 184, 146));
        jpSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jpSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 90));

        jpOpciones.setBackground(new java.awt.Color(139, 184, 146));
        jpOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCompras.setBackground(new java.awt.Color(69, 73, 75));
        jbtnCompras.setForeground(new java.awt.Color(187, 187, 188));
        jbtnCompras.setText("Compras");
        jbtnCompras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.add(jbtnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 40));

        jbtnVentas.setBackground(new java.awt.Color(69, 73, 75));
        jbtnVentas.setForeground(new java.awt.Color(187, 187, 188));
        jbtnVentas.setText("Ventas");
        jbtnVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.add(jbtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 40));

        jbtnClientes.setBackground(new java.awt.Color(69, 73, 75));
        jbtnClientes.setForeground(new java.awt.Color(187, 187, 188));
        jbtnClientes.setText("Clientes");
        jbtnClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.add(jbtnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 40));

        jbtnUsuarios.setBackground(new java.awt.Color(69, 73, 75));
        jbtnUsuarios.setForeground(new java.awt.Color(187, 187, 188));
        jbtnUsuarios.setText("Usuarios");
        jbtnUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.add(jbtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 40));

        jbtnProductos.setBackground(new java.awt.Color(69, 73, 75));
        jbtnProductos.setForeground(new java.awt.Color(187, 187, 188));
        jbtnProductos.setText("Productos");
        jbtnProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.add(jbtnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 40));

        jbtnProveedores.setBackground(new java.awt.Color(69, 73, 75));
        jbtnProveedores.setForeground(new java.awt.Color(187, 187, 188));
        jbtnProveedores.setText("Proveedores");
        jbtnProveedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.add(jbtnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, 40));

        jbtnAlmacen.setBackground(new java.awt.Color(69, 73, 75));
        jbtnAlmacen.setForeground(new java.awt.Color(187, 187, 188));
        jbtnAlmacen.setText("Almacen");
        jbtnAlmacen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpOpciones.add(jbtnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 40));

        getContentPane().add(jpOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 420));

        jdpContenerdor.setBackground(new java.awt.Color(69, 73, 75));
        jdpContenerdor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jdpContenerdor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 690, 420));

        jMenuBar1.setBackground(new java.awt.Color(69, 73, 75));

        jMenu1.setForeground(new java.awt.Color(187, 187, 188));
        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(187, 187, 188));
        jMenu2.setText("Opciones");

        jMenuItem1.setText("Administrar Usuarios");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Administrar Proveedores");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JButton jbtnAlmacen;
    public javax.swing.JButton jbtnClientes;
    public javax.swing.JButton jbtnCompras;
    public javax.swing.JButton jbtnProductos;
    public javax.swing.JButton jbtnProveedores;
    public javax.swing.JButton jbtnUsuarios;
    public javax.swing.JButton jbtnVentas;
    public javax.swing.JDesktopPane jdpContenerdor;
    private javax.swing.JPanel jpOpciones;
    private javax.swing.JPanel jpSuperior;
    // End of variables declaration//GEN-END:variables
}
