/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.softwarebodega.vista;

import java.awt.Color;

/**
 *
 * @author Aaron
 */
public class ProductoVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductoVista
     */
    public ProductoVista() {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jlblNombre = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jlblCategoria = new javax.swing.JLabel();
        jtxtCategoria = new javax.swing.JTextField();
        jlblMarca = new javax.swing.JLabel();
        jtxtMarca = new javax.swing.JTextField();
        jlblStockInicial = new javax.swing.JLabel();
        jtxtStockInicial = new javax.swing.JTextField();
        jlblStockMinimo = new javax.swing.JLabel();
        jtxtStockMinimo = new javax.swing.JTextField();
        jlblPrecioCosto = new javax.swing.JLabel();
        jtxtPrecioCosto = new javax.swing.JTextField();
        jlblUtilidad = new javax.swing.JLabel();
        jtxtUtilidad = new javax.swing.JTextField();
        jlblPrecioVenta = new javax.swing.JLabel();
        jtxtPrecioVenta = new javax.swing.JTextField();
        jlblFoto = new javax.swing.JLabel();
        jbtnCrear = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(69, 73, 75));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(187, 187, 188));
        jlblTitulo.setText("REGISTRAR PRODUCTO");
        getContentPane().add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 210, 40));

        jlblNombre.setForeground(new java.awt.Color(187, 187, 188));
        jlblNombre.setText("Nombre:");
        getContentPane().add(jlblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 30));

        jtxtNombre.setBackground(new java.awt.Color(69, 73, 75));
        jtxtNombre.setForeground(new java.awt.Color(187, 187, 188));
        jtxtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, 30));

        jlblCategoria.setForeground(new java.awt.Color(187, 187, 188));
        jlblCategoria.setText(" Categoría:");
        getContentPane().add(jlblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 30));

        jtxtCategoria.setBackground(new java.awt.Color(69, 73, 75));
        jtxtCategoria.setForeground(new java.awt.Color(187, 187, 188));
        jtxtCategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 30));

        jlblMarca.setForeground(new java.awt.Color(187, 187, 188));
        jlblMarca.setText("   Marca:");
        getContentPane().add(jlblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 30));

        jtxtMarca.setBackground(new java.awt.Color(69, 73, 75));
        jtxtMarca.setForeground(new java.awt.Color(187, 187, 188));
        jtxtMarca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, 30));

        jlblStockInicial.setForeground(new java.awt.Color(187, 187, 188));
        jlblStockInicial.setText("Stock Inicial:");
        getContentPane().add(jlblStockInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 80, 30));

        jtxtStockInicial.setBackground(new java.awt.Color(69, 73, 75));
        jtxtStockInicial.setForeground(new java.awt.Color(187, 187, 188));
        jtxtStockInicial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtStockInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 160, 30));

        jlblStockMinimo.setForeground(new java.awt.Color(187, 187, 188));
        jlblStockMinimo.setText("Stock Mínimo:");
        getContentPane().add(jlblStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 90, 30));

        jtxtStockMinimo.setBackground(new java.awt.Color(69, 73, 75));
        jtxtStockMinimo.setForeground(new java.awt.Color(187, 187, 188));
        jtxtStockMinimo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 160, 30));

        jlblPrecioCosto.setForeground(new java.awt.Color(187, 187, 188));
        jlblPrecioCosto.setText(" Precio Costo:");
        getContentPane().add(jlblPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 80, 30));

        jtxtPrecioCosto.setBackground(new java.awt.Color(69, 73, 75));
        jtxtPrecioCosto.setForeground(new java.awt.Color(187, 187, 188));
        jtxtPrecioCosto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 160, 30));

        jlblUtilidad.setForeground(new java.awt.Color(187, 187, 188));
        jlblUtilidad.setText(" Utilidad:");
        getContentPane().add(jlblUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 30));

        jtxtUtilidad.setBackground(new java.awt.Color(69, 73, 75));
        jtxtUtilidad.setForeground(new java.awt.Color(187, 187, 188));
        jtxtUtilidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 30));

        jlblPrecioVenta.setForeground(new java.awt.Color(187, 187, 188));
        jlblPrecioVenta.setText(" Precio Venta:");
        getContentPane().add(jlblPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 80, 30));

        jtxtPrecioVenta.setBackground(new java.awt.Color(69, 73, 75));
        jtxtPrecioVenta.setForeground(new java.awt.Color(187, 187, 188));
        jtxtPrecioVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 160, 30));

        jlblFoto.setBackground(new java.awt.Color(69, 73, 75));
        jlblFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 140, 180));

        jbtnCrear.setBackground(new java.awt.Color(69, 73, 75));
        jbtnCrear.setForeground(new java.awt.Color(187, 187, 188));
        jbtnCrear.setText("Crear");
        jbtnCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jbtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 110, 60));

        jbtnCancelar.setBackground(new java.awt.Color(69, 73, 75));
        jbtnCancelar.setForeground(new java.awt.Color(187, 187, 188));
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 110, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtnCancelar;
    public javax.swing.JButton jbtnCrear;
    private javax.swing.JLabel jlblCategoria;
    public javax.swing.JLabel jlblFoto;
    private javax.swing.JLabel jlblMarca;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblPrecioCosto;
    private javax.swing.JLabel jlblPrecioVenta;
    private javax.swing.JLabel jlblStockInicial;
    private javax.swing.JLabel jlblStockMinimo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblUtilidad;
    public javax.swing.JTextField jtxtCategoria;
    public javax.swing.JTextField jtxtMarca;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtPrecioCosto;
    public javax.swing.JTextField jtxtPrecioVenta;
    public javax.swing.JTextField jtxtStockInicial;
    public javax.swing.JTextField jtxtStockMinimo;
    public javax.swing.JTextField jtxtUtilidad;
    // End of variables declaration//GEN-END:variables
}
