/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.softwarebodega.vista;

/**
 *
 * @author Aaron
 */
public class ProveedorVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProveedorVista
     */
    public ProveedorVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jlblRUC = new javax.swing.JLabel();
        jlblNombre = new javax.swing.JLabel();
        jlblDireccion = new javax.swing.JLabel();
        jtxtRUC = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jlblCiudad = new javax.swing.JLabel();
        jlblCorreo = new javax.swing.JLabel();
        jlblTelefono = new javax.swing.JLabel();
        jtxtCiudad = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jlblObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaObservaciones = new javax.swing.JTextArea();
        jbtnCrear = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jtxtCorreo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(69, 73, 75));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(187, 187, 188));
        jlblTitulo.setText("CREAR PROVEEDOR");
        getContentPane().add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 180, 40));

        jlblRUC.setForeground(new java.awt.Color(187, 187, 188));
        jlblRUC.setText("RUC:");
        getContentPane().add(jlblRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 30));

        jlblNombre.setForeground(new java.awt.Color(187, 187, 188));
        jlblNombre.setText("Nombre:");
        getContentPane().add(jlblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 30));

        jlblDireccion.setForeground(new java.awt.Color(187, 187, 188));
        jlblDireccion.setText("Dirección:");
        getContentPane().add(jlblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, 30));

        jtxtRUC.setBackground(new java.awt.Color(69, 73, 75));
        jtxtRUC.setForeground(new java.awt.Color(187, 187, 188));
        jtxtRUC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, 30));

        jtxtNombre.setBackground(new java.awt.Color(69, 73, 75));
        jtxtNombre.setForeground(new java.awt.Color(187, 187, 188));
        jtxtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, 30));

        jtxtDireccion.setBackground(new java.awt.Color(69, 73, 75));
        jtxtDireccion.setForeground(new java.awt.Color(187, 187, 188));
        jtxtDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 30));

        jlblCiudad.setForeground(new java.awt.Color(187, 187, 188));
        jlblCiudad.setText("  Ciudad:");
        getContentPane().add(jlblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 50, 30));

        jlblCorreo.setForeground(new java.awt.Color(187, 187, 188));
        jlblCorreo.setText("  Correo:");
        getContentPane().add(jlblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 50, 30));

        jlblTelefono.setForeground(new java.awt.Color(187, 187, 188));
        jlblTelefono.setText("  Teléfono:");
        getContentPane().add(jlblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 60, 30));

        jtxtCiudad.setBackground(new java.awt.Color(69, 73, 75));
        jtxtCiudad.setForeground(new java.awt.Color(187, 187, 188));
        jtxtCiudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 180, 30));

        jtxtTelefono.setBackground(new java.awt.Color(69, 73, 75));
        jtxtTelefono.setForeground(new java.awt.Color(187, 187, 188));
        jtxtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 180, 30));

        jlblObservaciones.setForeground(new java.awt.Color(187, 187, 188));
        jlblObservaciones.setText("Observaciones:");
        getContentPane().add(jlblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 30));

        jtaObservaciones.setBackground(new java.awt.Color(69, 73, 75));
        jtaObservaciones.setColumns(20);
        jtaObservaciones.setForeground(new java.awt.Color(187, 187, 188));
        jtaObservaciones.setRows(5);
        jtaObservaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jtaObservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 460, 80));

        jbtnCrear.setBackground(new java.awt.Color(69, 73, 75));
        jbtnCrear.setForeground(new java.awt.Color(187, 187, 188));
        jbtnCrear.setText("Crear");
        jbtnCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jbtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 110, 60));

        jbtnCancelar.setBackground(new java.awt.Color(69, 73, 75));
        jbtnCancelar.setForeground(new java.awt.Color(187, 187, 188));
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 110, 60));

        jtxtCorreo.setBackground(new java.awt.Color(69, 73, 75));
        jtxtCorreo.setForeground(new java.awt.Color(187, 187, 188));
        jtxtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnCancelar;
    public javax.swing.JButton jbtnCrear;
    private javax.swing.JLabel jlblCiudad;
    private javax.swing.JLabel jlblCorreo;
    private javax.swing.JLabel jlblDireccion;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblObservaciones;
    private javax.swing.JLabel jlblRUC;
    private javax.swing.JLabel jlblTelefono;
    private javax.swing.JLabel jlblTitulo;
    public javax.swing.JTextArea jtaObservaciones;
    public javax.swing.JTextField jtxtCiudad;
    public javax.swing.JTextField jtxtCorreo;
    public javax.swing.JTextField jtxtDireccion;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtRUC;
    public javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
