/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.softwarebodega.vista;

/**
 *
 * @author Aaron
 */
public class UsuarioVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioVista
     */
    public UsuarioVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblContraseña = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jlblNombre = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jlblApellido = new javax.swing.JLabel();
        jtxtApellido = new javax.swing.JTextField();
        jlblTelefono = new javax.swing.JLabel();
        jlblCorreo = new javax.swing.JLabel();
        jtxtCorreo = new javax.swing.JTextField();
        jlblCondicion = new javax.swing.JLabel();
        jpfContraseña = new javax.swing.JPasswordField();
        jlblUsuario = new javax.swing.JLabel();
        jcbCondicion = new javax.swing.JComboBox<>();
        jbtnCancelar = new javax.swing.JButton();
        jbtnCrear = new javax.swing.JButton();
        jlblTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(69, 73, 75));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblContraseña.setForeground(new java.awt.Color(187, 187, 188));
        jlblContraseña.setText(" Contraseña:");
        getContentPane().add(jlblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 80, 30));

        jtxtTelefono.setBackground(new java.awt.Color(69, 73, 75));
        jtxtTelefono.setForeground(new java.awt.Color(187, 187, 188));
        jtxtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 120, 30));

        jtxtUsuario.setBackground(new java.awt.Color(69, 73, 75));
        jtxtUsuario.setForeground(new java.awt.Color(187, 187, 188));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 120, 30));

        jlblNombre.setForeground(new java.awt.Color(187, 187, 188));
        jlblNombre.setText("Nombre:");
        getContentPane().add(jlblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 30));

        jtxtNombre.setBackground(new java.awt.Color(69, 73, 75));
        jtxtNombre.setForeground(new java.awt.Color(187, 187, 188));
        jtxtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, 30));

        jlblApellido.setForeground(new java.awt.Color(187, 187, 188));
        jlblApellido.setText("Apellido:");
        getContentPane().add(jlblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));

        jtxtApellido.setBackground(new java.awt.Color(69, 73, 75));
        jtxtApellido.setForeground(new java.awt.Color(187, 187, 188));
        jtxtApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, 30));

        jlblTelefono.setForeground(new java.awt.Color(187, 187, 188));
        jlblTelefono.setText("Teléfono:");
        getContentPane().add(jlblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        jlblCorreo.setForeground(new java.awt.Color(187, 187, 188));
        jlblCorreo.setText("  Correo:");
        getContentPane().add(jlblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 50, 30));

        jtxtCorreo.setBackground(new java.awt.Color(69, 73, 75));
        jtxtCorreo.setForeground(new java.awt.Color(187, 187, 188));
        jtxtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, 30));

        jlblCondicion.setForeground(new java.awt.Color(187, 187, 188));
        jlblCondicion.setText(" Condición:");
        getContentPane().add(jlblCondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, 30));

        jpfContraseña.setBackground(new java.awt.Color(69, 73, 75));
        jpfContraseña.setForeground(new java.awt.Color(187, 187, 188));
        jpfContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jpfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 120, 30));

        jlblUsuario.setForeground(new java.awt.Color(187, 187, 188));
        jlblUsuario.setText(" Usuario:");
        getContentPane().add(jlblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 50, 30));

        jcbCondicion.setBackground(new java.awt.Color(69, 73, 75));
        jcbCondicion.setForeground(new java.awt.Color(187, 187, 188));
        jcbCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Administrador", "Usuario" }));
        jcbCondicion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jcbCondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 120, 30));

        jbtnCancelar.setBackground(new java.awt.Color(69, 73, 75));
        jbtnCancelar.setForeground(new java.awt.Color(187, 187, 188));
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 110, 60));

        jbtnCrear.setBackground(new java.awt.Color(69, 73, 75));
        jbtnCrear.setForeground(new java.awt.Color(187, 187, 188));
        jbtnCrear.setText("Crear");
        jbtnCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jbtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 110, 60));

        jlblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(187, 187, 188));
        jlblTitulo.setText("CREAR USUARIO");
        getContentPane().add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtnCancelar;
    public javax.swing.JButton jbtnCrear;
    public javax.swing.JComboBox<String> jcbCondicion;
    private javax.swing.JLabel jlblApellido;
    private javax.swing.JLabel jlblCondicion;
    private javax.swing.JLabel jlblContraseña;
    private javax.swing.JLabel jlblCorreo;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblTelefono;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblUsuario;
    public javax.swing.JPasswordField jpfContraseña;
    public javax.swing.JTextField jtxtApellido;
    public javax.swing.JTextField jtxtCorreo;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtTelefono;
    public javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
